### PR TITLE
Add status error type

### PR DESCRIPTION
**Pull request by kgilles**
The [API will forward the HTTP status](https://github.com/sublinks/sublinks-api/blob/0b43d6a850053797ace5f80f38f1217e9c80e42b/src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/errorhandler/ApiError.java#L12) in the error response to the client. This updates the types to make TS happy.

### CODE REVIEW

**Comment by asimons04** [comment]
All look good except BanFromCommunityResponse.ts

`status` is doubled up and has 2 commas

```
  status?: string,,
  status?: string,
```

**Comment by asimons04** [comment]
Do you want to fix that and re-submit the PR?  Or I can merge it as-is, fix the duplicated key, and then rebuild the NPM package.

**Comment by kgilles** [comment]
> All look good except BanFromCommunityResponse.ts
> 
> `status` is doubled up and has 2 commas
> 
> ```
>   status?: string,,
>   status?: string,
> ```

@asimons04  Looks alright to me
https://github.com/sublinks/sublinks-js-client/blob/cab26272d2345d70c17e4f267c1051c71d6ac2bc/src/types/lemmy/BanFromCommunityResponse.ts

Screenshot 2024-05-22 at 4 00 44 PM

**Comment by asimons04** [comment]
Sorry, my bad.  Looks like it got fixed in the commit to update the docs (assumed that was just the commit with the typedoc output).

**Comment by asimons04** [comment]
NPM package 0.0.18 built and published.

**Pull request merged**
